/**
 * Urban Authority design tokens.
 * Ported verbatim from the tailwind.config block in design/code.html — keep in sync with
 * design/DESIGN.md. Do not hand-tune values here; change the design system first.
 */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './content/**/*.md'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface-variant': '#4d453f',
        'error-container': '#ffdad6',
        'on-secondary': '#ffffff',
        primary: '#42362b',
        'on-primary-fixed': '#231a10',
        'on-tertiary-fixed': '#201b0d',
        surface: '#fcf9f8',
        'warm-parchment': '#E9E3B4',
        'on-tertiary-container': '#ccc1ab',
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'surface-container-lowest': '#ffffff',
        'on-background': '#1c1b1b',
        background: '#fcf9f8',
        tertiary: '#3f3828',
        'inverse-on-surface': '#f3f0ef',
        secondary: '#00629e',
        'on-tertiary-fixed-variant': '#4d4635',
        'tertiary-fixed-dim': '#d0c5af',
        'surface-tint': '#6a5c4f',
        'brick-accent': '#B33939',
        'slate-infrastructure': '#2D3436',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#313030',
        'secondary-fixed': '#cfe5ff',
        'on-primary': '#ffffff',
        'surface-container': '#f0eded',
        'tertiary-fixed': '#ede1ca',
        'secondary-container': '#69b6fe',
        'primary-container': '#5a4d41',
        'on-primary-fixed-variant': '#514439',
        'surface-dim': '#dcd9d9',
        'on-surface': '#1c1b1b',
        'on-secondary-fixed-variant': '#004a79',
        'inverse-primary': '#d6c3b4',
        'primary-fixed-dim': '#d6c3b4',
        outline: '#7f756e',
        'surface-variant': '#e5e2e1',
        'on-secondary-fixed': '#001d34',
        'on-secondary-container': '#004673',
        'surface-bright': '#fcf9f8',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'on-error': '#ffffff',
        'outline-variant': '#d0c4bb',
        'surface-container-low': '#f6f3f2',
        'on-primary-container': '#d0beaf',
        'secondary-fixed-dim': '#9acbff',
        'tertiary-container': '#564f3d',
        'primary-fixed': '#f2dfcf',
      },
      borderRadius: {
        // Shape language is Sharp (0px) — these exist only for the rare pill/avatar.
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'section-gap': '80px',
        'stack-lg': '48px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        'stack-sm': '8px',
        'stack-md': '24px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        caption: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'headline-md': ['"Source Serif 4 Variable"', '"Source Serif 4"', 'Georgia', 'serif'],
        'label-caps': ['JetBrains Mono', 'ui-monospace', 'monospace'],
        'display-lg-mobile': ['"Source Serif 4 Variable"', '"Source Serif 4"', 'Georgia', 'serif'],
        'display-lg': ['"Source Serif 4 Variable"', '"Source Serif 4"', 'Georgia', 'serif'],
        'body-md': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'system-ui', 'sans-serif'],
        'headline-sm': ['"Source Serif 4 Variable"', '"Source Serif 4"', 'Georgia', 'serif'],
      },
      fontSize: {
        caption: ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
